### ISSUE TITLE
validate#87

### ISSUE THREAD

**Issue by MartijnR** [OpenClinica/enketo-express-oc#391]

**Comment by MartijnR** [comment]
https://github.com/enketo/enketo-validate/issues/87

**Comment by MartijnR** [comment]
Also a different issue in Enketo Core: 

```
enketo-bundle.js:24050 Uncaught FormLogicError {message: "Could not evaluate: /model/instance[1]/data/rep/ /…pression. (line: undefined, character: undefined)", name: "FormLogicError", stack: "Error↵    at new FormLogicError (http://localhost:…ttp://localhost:8005/js/enketo-bundle.js:53635:35"}message: "Could not evaluate: /model/instance[1]/data/rep/ /model/instance[1]/data/rep/three, message: The expression is not a legal expression. (line: undefined, character: undefined)"name: "FormLogicError"stack: "Error↵    at new FormLogicError (http://localhost:8005/js/enketo-bundle.js:1334:24)↵    at FormModel.evaluate (http://localhost:8005/js/enketo-bundle.js:24050:23)↵    at Nodeset.getElements (http://localhost:8005/js/enketo-bundle.js:12984:38)↵    at http://localhost:8005/js/enketo-bundle.js:52517:48↵    at Array.forEach (<anonymous>)↵    at Object.setValue (http://localhost:8005/js/enketo-bundle.js:52514:19)↵    at HTMLFormElement.<anonymous> (http://localhost:8005/js/enketo-bundle.js:53111:95)↵    at http://localhost:8005/js/enketo-bundle.js:53635:35"__proto__: Error
FormModel.evaluate @ enketo-bundle.js:24050
Nodeset.getElements @ enketo-bundle.js:12984
(anonymous) @ enketo-bundle.js:52517
setValue @ enketo-bundle.js:52514
(anonymous) @ enketo-bundle.js:53111
(anonymous) @ enketo-bundle.js:53635
Promise.then (async)
(anonymous) @ enketo-bundle.js:53633
dispatch @ enketo-bundle.js:7515
elemData.handle @ enketo-bundle.js:7319
```

**Comment by MartijnR** [comment]
<img width="687" alt="Screen Shot 2020-11-16 at 1 27 56 PM" src="https://user-images.githubusercontent.com/627350/99304412-92f3be00-280f-11eb-906f-3f8e5f364e89.png">

See incorrect path

**Comment by MartijnR** [comment]
* [ ] pyxform fix and merge
* [ ] Martijn to propagate fix for spaces in ref attribute

**Comment by pbowen-oc** [comment]
Closing here to finalize tracking of this issue in the Validate issue list.
