### ISSUE TITLE
SyntaxError from html.js of master branch of enketo-validate

### ISSUE THREAD

**Issue by iwoodferren** [OpenClinica/enketo-express-oc#589]
After running npm install and the following command a SyntaxError was generated.

COMMAND:
/opt/applications/enketo-validate/validate -oc /home/java_svc/STORAGE/98fcd250-428f-44d2-8c8f-24397f88003f/form.xml

ERROR:
/opt/applications/enketo-validate/node_modules/jsdom/lib/jsdom/browser/parser/html.js:170
    after._pushedOnStackOfOpenElements?.();
                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/applications/enketo-validate/node_modules/jsdom/lib/jsdom/browser/parser/index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by iwoodferren** [comment]
currently OC is using 1.14.2, which is still working. The SyntaxError was found in 1.15.2

**Comment by iwoodferren** [comment]
Hello @MartijnR 

yes I am pulling from the git repo and building the master branch using the npm install command I posted earlier.

It is not form specific as any form will produce this error. Here's on as an example: 
[vitals-grid_v1.xls](https://github.com/OpenClinica/enketo-express-oc/files/9600207/vitals-grid_v1.xls)

**Comment by iwoodferren** [comment]
Apologies. Here is the xform: 
[form (copy).txt](https://github.com/OpenClinica/enketo-express-oc/files/9600673/form.copy.txt)

**Comment by MartijnR** [comment]
Got, it seems to occur in node 12. I thought I had been testing with node 12. Sorry.  Node 14 is fine.

* [ ] check if we can bring back compatibility with node 12

**Comment by MartijnR** [comment]
@iwoodferren, I fixed node 12 compatibility in version 1.15.3. 

I also published version 2.0.0 that drops node 12 compatibility properly (and requires node 14 or 16). You may want to just go straight to 2.0.0 if you have no strong reason to stick with node 12.

**Comment by iwoodferren** [comment]
@MartijnR Thanks for the assist! I will test as soon as the change is merged.

**Comment by MartijnR** [comment]
Merged!

**Comment by iwoodferren** [comment]
Thanks!
